version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3
    container_name: "rabbitmq-invictus-capital"
    ports:
      - 5672:5672

  utilities:
    build: ./utilities
    restart: always
    depends_on:
      - rabbitmq
